### PR TITLE
clarify why you can omit `node_modules/.bin` in npm scripts

### PR DESCRIPTION
**Pull request by rooberrydev**
Previous wording said "npm automatically includes this directory" which I don't think was clear enough.
Added some extra descriptive text.

### CODE REVIEW

**Review by oliverjam — APPROVED** [review]
This is a great update, thank you!

I have wondered for a while if we should mention `npx` in here somewhere too. Since it's a way to get the same behaviour in your terminal as in npm scripts (`npx cowsay` will go use the installed bin). However there's the extra complication of "if it doesn't find it locally it'll download it from the internet 😅)

**Comment by reubengt** [comment]
Is `npx create-react-app` the first time students encounter `npx`?

**Comment by reubengt** [comment]
Oh there's actually a research topic in node week covering npx

**Comment by oliverjam** [comment]
Yeah I made it a spike topic because I originally judged this npm intro was already kinda information-overload

**Pull request merged**
